"""artifact fk issues

Revision ID: 053679cc996c
Revises: 4485158c8f14
Create Date: 2026-02-12 15:46:13.000131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053679cc996c'
down_revision: Union[str, Sequence[str], None] = '4485158c8f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('parent_artifact', sa.UUID(), nullable=True))
    op.add_column('artifacts', sa.Column('museum_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'artifacts', 'museums', ['museum_id'], ['museum_id'])
    op.create_foreign_key(None, 'artifacts', 'artifacts', ['parent_artifact'], ['artifact_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'museum_id')
    op.drop_column('artifacts', 'parent_artifact')
    # ### end Alembic commands ###
