"""init

Revision ID: 11fac970e3bc
Revises: 
Create Date: 2026-02-11 18:40:01.243117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11fac970e3bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('condition_rating', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('museums',
    sa.Column('museum_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('museum_id')
    )
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('discovery_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_value', sa.Integer(), nullable=True),
    sa.Column('parent_artifact', sa.UUID(), nullable=True),
    sa.Column('museum_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.museum_id'], ),
    sa.ForeignKeyConstraint(['parent_artifact'], ['artifacts.artifact_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_table('loans',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('loan_status', sa.String(), nullable=False),
    sa.Column('insurance_value', sa.String(), nullable=False),
    sa.Column('to_museum_id', sa.UUID(), nullable=False),
    sa.Column('from_museum_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['from_museum_id'], ['museums.museum_id'], ),
    sa.ForeignKeyConstraint(['to_museum_id'], ['museums.museum_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('artifact_loans',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('display_requirements', sa.String(), nullable=True),
    sa.Column('return_condition_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.loan_id'], ),
    sa.PrimaryKeyConstraint('artifact_id', 'loan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact_loans')
    op.drop_table('loans')
    op.drop_table('artifacts')
    op.drop_table('museums')
    op.drop_table('condition_reports')
    # ### end Alembic commands ###
