"""artifact fk issues

Revision ID: 4485158c8f14
Revises: d3495306492c
Create Date: 2026-02-12 15:42:47.735023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4485158c8f14'
down_revision: Union[str, Sequence[str], None] = 'd3495306492c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artifact_id_fk_removal'), 'artifact_loans', type_='foreignkey')
    op.drop_constraint(op.f('loan_id_fk_removal'), 'artifact_loans', type_='foreignkey')
    op.drop_constraint(op.f('artifacts_museum_id_fkey'), 'artifacts', type_='foreignkey')
    op.drop_constraint(op.f('artifacts_parent_artifact_fkey'), 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'museum_id')
    op.drop_column('artifacts', 'parent_artifact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('parent_artifact', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('artifacts', sa.Column('museum_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('artifacts_parent_artifact_fkey'), 'artifacts', 'artifacts', ['parent_artifact'], ['artifact_id'])
    op.create_foreign_key(op.f('artifacts_museum_id_fkey'), 'artifacts', 'museums', ['museum_id'], ['museum_id'])
    op.create_foreign_key(op.f('loan_id_fk_removal'), 'artifact_loans', 'loans', ['loan_id'], ['loan_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('artifact_id_fk_removal'), 'artifact_loans', 'artifacts', ['artifact_id'], ['artifact_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
