"""finalized constraints and schemas

Revision ID: b46f5669dabf
Revises: 053679cc996c
Create Date: 2026-02-18 19:57:57.281896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46f5669dabf'
down_revision: Union[str, Sequence[str], None] = '053679cc996c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artifact_loans_loan_id_fkey'), 'artifact_loans', type_='foreignkey')
    op.drop_constraint(op.f('artifact_loans_artifact_id_fkey'), 'artifact_loans', type_='foreignkey')
    op.create_foreign_key(None, 'artifact_loans', 'loans', ['loan_id'], ['loan_id'])
    op.create_foreign_key(None, 'artifact_loans', 'artifacts', ['artifact_id'], ['artifact_id'])
    op.drop_constraint(op.f('condition_reports_artifact_id_fkey'), 'condition_reports', type_='foreignkey')
    op.create_foreign_key(None, 'condition_reports', 'artifacts', ['artifact_id'], ['artifact_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'condition_reports', type_='foreignkey')
    op.create_foreign_key(op.f('condition_reports_artifact_id_fkey'), 'condition_reports', 'artifacts', ['artifact_id'], ['artifact_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'artifact_loans', type_='foreignkey')
    op.drop_constraint(None, 'artifact_loans', type_='foreignkey')
    op.create_foreign_key(op.f('artifact_loans_artifact_id_fkey'), 'artifact_loans', 'artifacts', ['artifact_id'], ['artifact_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('artifact_loans_loan_id_fkey'), 'artifact_loans', 'loans', ['loan_id'], ['loan_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
