"""fix condition reports

Revision ID: d3495306492c
Revises: 18a9905d4ebb
Create Date: 2026-02-12 15:09:31.025350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3495306492c'
down_revision: Union[str, Sequence[str], None] = '18a9905d4ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condition_reports', sa.Column('artifact_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'condition_reports', 'artifacts', ['artifact_id'], ['artifact_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'condition_reports', type_='foreignkey')
    op.drop_column('condition_reports', 'artifact_id')
    # ### end Alembic commands ###
